# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('user__first_name',)},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='work',
            name='fee',
            field=models.FloatField(),
        ),
    ]
