# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_client', '0002_auto_20171215_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
